### ISSUE TITLE
Active development?

### ISSUE THREAD

**Issue by tommyw** [rasmusjp/umbraco-graphql#46]
Hi @rasmusjp 

Is this still under active development? 
Are you intending on rolling GraphQL into Umbraco Headless?

If you are no longer working on this project, do you mind me forking it, so that we can try to provide a full, open source GraphQL implementation for our favourite CMS?

Thanks

Tom

**Comment by rasmusjp** [comment]
Hi Tom

I've just picked up development again last week where I got the project running on Umbraco 8.1 and right now am in the process of refactoring and cleaning up the code, so I'll hopefully have something that's easier to work with soon.

We are planning on implementing GraphQL in Umbraco Headless, but it won't be based on this project since we are looking into building a distributed, highly available, multi tenant solution, which most likely wont be something we can package up.

It's my intention to keep supporting this project and I'll happily accept any help I can get, feel free to fork and play around with it and come with suggestions.

**Comment by PeteDuncanson** [comment]
I paused work on this as I didn't know what HQ were going to do with their version for Headless. That sounds like its going to be a black box so keeping this project alive is essential I think.

I'd also love to see if we can't get the back office running off GraphQL too :)

**Comment by rasmusjp** [comment]
Hi @tommyw 

Sorry for the silence. I've just pushed a major rewrite to the `develop` branch.
