### ISSUE TITLE
What's the syntax for filtering queries?

### ISSUE THREAD

**Issue by dchallener** [rasmusjp/umbraco-graphql#53]
Hi,

I'm massively struggling to work out the syntax for filtering a result set with the in-built filters.  Are you able to provide a sample query for returning filtered nodes from Umbraco?

For example, with a custom node called book in Umbraco and bookDirectory being the parent folder of books, what should the query be?  I've tried lots of combinations, but not getting anything valid! 

```
{
  umbraco {
    content {
      byType {
        bookDirectory {
          pageTitle
          bookStartsWithA: _children(
            filter: { _name_starts_with: "A" }
            orderBy: _name_ASC
          ) {
            items {
              ... on BookPublishedContent {
                _name
                author
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by rasmusjp** [comment]
Hi @dchallener 

Looking at the query I'm assuming you are using the latest version from the develop branch.

Filtering isn't implemented yet as I wanted to rethink how they should work. I don't think the current implementation in the Umbraco 7 version is very useful (it was only included as a POC) since you can only filter on fields that are "known" (ordering has the same problem).

What I'm thinking of is making the "field" part a string you pass in, it might look something like this:
```graphql
{
  umbraco {
    content {
      byType {
        bookDirectory {
          pageTitle
          bookStartsWithA: _children(
            filter: [{ field: "_name", op: STARTS_WITH, value: "A" }
            orderBy: "_name"
            sortOrder: ASC
          ) {
            items {
              ... on BookPublishedContent {
                _name
                author
              }
            }
          }
        }
      }
    }
  }
}
```

This would not only make the backing code more simple (I think) but also allow you to filter on fields like `author`.

Only drawback is that it's not strongly typed so you might end up with spelling mistakes, but I think the flexibility of being able to pass in every field outweighs that

**Comment by rasmusjp** [comment]
Hi

Just wanted to let you know that the project is moving to the [Umbraco Community](https://github.com/umbraco-community/) GitHub organisation, so we are closing all existing issues.

If you think your issue is still relevant, please feel free to reopen it.

/Rasmus
